ceph-deploy disk zap vmon1:/dev/sdc
ceph-deploy osd prepare vmon1:/dev/sdc:/dev/sdb1
ceph-deploy osd activate vmon1:/dev/sdc1:/dev/sdb1
ceph-deploy disk zap vmon1:/dev/sdd
ceph-deploy osd prepare vmon1:/dev/sdd:/dev/sdb2
ceph-deploy osd activate vmon1:/dev/sdd1:/dev/sdb2
ceph-deploy disk zap vmon1:/dev/sde
ceph-deploy osd prepare vmon1:/dev/sde:/dev/sdb3
ceph-deploy osd activate vmon1:/dev/sde1:/dev/sdb3
